### ISSUE TITLE
Unable to enter license code

### ISSUE THREAD

**Issue by CryptLabs** [abulka/pynsource#109]
Hello,

I'm having trouble entering the the licence code. When I click on "Enter License"  in the help menu, nothing happens.

Please help ASAP.

Kind regards.

**Comment by abulka** [comment]
I don't have any experience with Arch (though the recent M1 breakthrough is very interesting). The Pynsource binary has been built for Debian/Ubuntu - seems that it's somehow miraculously running on Arch but just the rego is not working.

For Unix rego, we follow the XDG spec and support $XDG_DATA_HOME.    That means, by default "~/.local/share/<AppName>" - pesumably there is no problem creating that path. 

I'd have to install Arch in a VM to investigate further.

**Comment by CryptLabs** [comment]
I have downloaded the Ubuntu binary and run the pynsource file. The application works and I were able to enter the license key. However, when I try to select anything from the menu, the app closes.
How can I make the app work on Arch Linux. Otherwise, the pro version is useless on other Linux distributions.

**Comment by abulka** [comment]
I just burnt the morning trying to install arch desktop in vmware, and then manjaro gnome in vmware - unsuccessfully, so I can't investigate any further. Pynsource has only been certified and tested in debian distros and I don't see that changing given the demand. There is a slightly older fedora build I made for someone, but that's all that has been requested.

The same python parsing and diagramming exists in the sister product www.gituml.com - if you like I can pro-rata a subscription to it based on what you have paid for Pynsource - or I can simply refund you.

**Comment by CryptLabs** [comment]
Hello,

I can help you modify it for Arch maybe.

These are images for VMWare and VBox

https://www.linuxvmimages.com/images/archlinux/


Kind Regards

Ali

**Comment by CryptLabs** [comment]
I got the same issue on Windows 11 also. After I enter the license code everything is ok. However, when I close and try to start the app it just closes by itself.

**Comment by abulka** [comment]
Thanks for the link to the pre-created VM images. I downloaded Manjaro OK and ran pynsource from the terminal

```
[manjaro@manjaro-21 Desktop]$ ./Pynsource 
Running Community Edition
LOG_FILENAME is /home/manjaro/.cache/pynsource/log/debug.log
Gtk-Message: 05:18:03.481: Failed to load module "xapp-gtk3-module"
Gtk-Message: 05:18:03.481: Failed to load module "canberra-gtk-module"
Gtk-Message: 05:18:03.521: Failed to load module "colorreload-gtk-module"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
05:18:03 AM: Debug: Adding duplicate image handler for 'PNG file'
05:18:03 AM: Debug: Adding duplicate image handler for 'JPEG file'
05:18:03 AM: Debug: Adding duplicate image handler for 'TIFF file'
05:18:03 AM: Debug: Adding duplicate image handler for 'GIF file'
05:18:03 AM: Debug: Adding duplicate image handler for 'PNM file'
05:18:03 AM: Debug: Adding duplicate image handler for 'PCX file'
05:18:03 AM: Debug: Adding duplicate image handler for 'IFF file'
05:18:03 AM: Debug: Adding duplicate image handler for 'Windows icon file'
05:18:03 AM: Debug: Adding duplicate image handler for 'Windows cursor file'
05:18:03 AM: Debug: Adding duplicate image handler for 'Windows animated cursor file'
05:18:03 AM: Debug: Adding duplicate image handler for 'TGA file'
05:18:03 AM: Debug: Adding duplicate image handler for 'XPM file'

(Pynsource:83403): Gtk-WARNING **: 05:18:03.708: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

Can you build pynsource from source code on Arch?  The build instructions are at https://github.com/abulka/pynsource and specifically https://github.com/abulka/pynsource/blob/master/BUILDING.md - I suspect we'd need a wxPython wheel specific to the distro - possibilities are currently https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ - googling wxPython and arch gave me https://archlinux.org/packages/community/x86_64/python-wxpython/ perhaps.

As for your windows 11 issue - that's odd. Please open another issue with more information. I am running it perfectly fine registered on windows 11. Can you run and use the program OK unregistered? What is in the terminal when you crash. What is in `pynsource/log/debug.log` (the location of which is reported in the terminal when you run pynsource) etc.

**Comment by CryptLabs** [comment]
I will try and let you know.

**Comment by uhu53** [comment]
@abulka 
may I ask what's the status of the issue?
many thanks

I'm on  FC35, python-3.10.7, wxPython 4.0.7; 
an attempt to enter the license number stalls; on the console:

s6> Running Community Edition
LOG_FILENAME is /home/uhu/.cache/pynsource/log/debug.log
21:26:31: Debug: Adding duplicate image handler for 'PNG file'
21:26:31: Debug: Adding duplicate image handler for 'JPEG file'
21:26:31: Debug: Adding duplicate image handler for 'TIFF file'
21:26:31: Debug: Adding duplicate image handler for 'GIF file'
21:26:31: Debug: Adding duplicate image handler for 'PNM file'
21:26:31: Debug: Adding duplicate image handler for 'PCX file'
21:26:31: Debug: Adding duplicate image handler for 'IFF file'
21:26:31: Debug: Adding duplicate image handler for 'Windows icon file'
21:26:31: Debug: Adding duplicate image handler for 'Windows cursor file'
21:26:31: Debug: Adding duplicate image handler for 'Windows animated cursor file'
21:26:31: Debug: Adding duplicate image handler for 'TGA file'
21:26:31: Debug: Adding duplicate image handler for 'XPM file'
no running event loop
Error checking for latest version during startup? Exception bypassed.
/opt/pynsource-1.84/src/pynsource-gui.py:379: RuntimeWarning: coroutine 'MainApp.check_for_updates' was never awaited
  print("Error checking for latest version during startup? Exception bypassed.")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/opt/pynsource-1.84/src/pynsource-gui.py:1632: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
Traceback (most recent call last):
  File "/opt/pynsource-1.84/src/pynsource-gui.py", line 1361, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license' from 'gui.settings' (/opt/pynsource-1.84/src/gui/settings.py)

**Comment by abulka** [comment]
@uhu53 Looks like you are trying to register a source code built version. You need to download a pynsource binary for Arch which contains the secret registration code - however we never ended up successfully compiling a binary for Arch. Thus pro pynsource is still currently unsupported on arch, sorry.

**Comment by CryptLabs** [comment]
Sorry for the late reply; I got caught up with many things.

**Comment by alikahaw** [comment]
```
ImportError: cannot import name 'enter_license'
Traceback (most recent call last):
  File "/snap/pynsource/24/pynsource-gui.py", line 1361, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license'
Traceback (most recent call last):
  File "/snap/pynsource/24/pynsource-gui.py", line 1361, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license'
```

**Comment by abulka** [comment]
Snaps can't be registered - you need to download the binary for Ubuntu.
