### ISSUE TITLE
run in ubuntu 

### ISSUE THREAD

**Issue by Kagev** [abulka/pynsource#118]
can you give solutions for ubuntu. how to install a non-snap package. because earlier, it was written by you that it is not possible to add a key about

I try to build - does not work. too many complexities. give a working program with the ability to add a paid key
I'm not sure that all these complexities are worth $ 20

`./Pynsource --no-antialiasing
Running Community Edition
LOG_FILENAME is /home/kagev/.cache/pynsource/log/debug.log

(Pynsource:56129): GLib-GIO-ERROR **: 18:15:47.677: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
`

**Comment by abulka** [comment]
Download the binary versions (there are newer betas available too) and you won't have any problems registering. You may need to quit and restart for the license to be recognised. 

You cannot register the community edition.

**Comment by Kagev** [comment]
with a lot of pain, I finally built it. 
how to solve this problem now:

`[Fri 11:13 AM] [INFO] common.logger - 120 - ------------------------------------------------------------
[Fri 11:13 AM] [INFO] common.logger - 121 - This LOG_FILENAME is /home/kagev/.cache/pynsource/log/debug.log
[Fri 11:13 AM] [INFO] common.logger - 122 - Python version sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
[Fri 11:17 am] [INFO] __main__ - 499 - Pynsource (configobj) config location /home/kagev/.Pynsource/pynsource.ini
[Fri 11:17 am] [INFO] __main__ - 528 - Pynsource (wx.FileConfig) config location /home/kagev/.Pynsource/pynsource_wx.ini
[Fri 11:17 am] [INFO] __main__ - 544 - Main config contents: {'keyword1': 100, 'keyword2': 'hi there', 'LastDirFileOpen': '/home/kagev/', 'LastDirFileImport': '/home/kagev/', 'LastDirInsertImage': '/home/kagev/'}
[Fri 11:17 am] [INFO] __main__ - 387 - Pynsource version 1.84 running, ASYNC=True, PRO=False
[Fri 11:17 am] [INFO] __main__ - 388 - wxPython version 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1`

`/bin/run
Running Community Edition
LOG_FILENAME is /home/kagev/.cache/pynsource/log/debug.log
11:01:17: Debug: Adding duplicate image handler for 'PNG file'
11:01:17: Debug: Adding duplicate image handler for 'JPEG file'
11:01:17: Debug: Adding duplicate image handler for 'TIFF file'
11:01:17: Debug: Adding duplicate image handler for 'GIF file'
11:01:17: Debug: Adding duplicate image handler for 'PNM file'
11:01:17: Debug: Adding duplicate image handler for 'PCX file'
11:01:17: Debug: Adding duplicate image handler for 'IFF file'
11:01:17: Debug: Adding duplicate image handler for 'Windows icon file'
11:01:17: Debug: Adding duplicate image handler for 'Windows cursor file'
11:01:17: Debug: Adding duplicate image handler for 'Windows animated cursor file'
11:01:17: Debug: Adding duplicate image handler for 'TGA file'
11:01:17: Debug: Adding duplicate image handler for 'XPM file'

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.654: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.655: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.655: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.655: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.655: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(pynsource-gui.py:3728): GLib-GObject-WARNING **: 11:01:17.655: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(pynsource-gui.py:3728): Gtk-CRITICAL **: 11:01:17.655: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
no running event loop
Error checking for latest version during startup? Exception bypassed.
/home/kagev/pynsource/src/pynsource-gui.py:379: RuntimeWarning: coroutine 'MainApp.check_for_updates' was never awaited
  print("Error checking for latest version during startup? Exception bypassed.")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/kagev/pynsource/src/pynsource-gui.py:1632: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
Traceback (most recent call last):
  File "/home/kagev/pynsource/src/pynsource-gui.py", line 1361, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license' from 'gui.settings' (/home/kagev/pynsource/src/gui/settings.py)
Traceback (most recent call last):
  File "/home/kagev/pynsource/src/pynsource-gui.py", line 1361, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license' from 'gui.settings' (/home/kagev/pynsource/src/gui/settings.py)
`

**Comment by abulka** [comment]
Please see my previous comment - you simply cannot register the community edition built from source code, it is missing all the libraries of the pro version incl the registration licensing code.

**Comment by Kagev** [comment]
I already purchased a key from the PRO version on your site.
what's next?

**Comment by abulka** [comment]
Download and install one of the binary Ubuntu deb installers from https://github.com/abulka/pynsource/releases/tag/pre-70 .  Run the app and register it using the licensing menu item. Restart the app to take full effect.
