### ISSUE TITLE
wxEntryStart failed, unable to initialize wxWidgets!

### ISSUE THREAD

**Issue by LukasWallisch** [abulka/pynsource#55]
When trying to launch it on Ubuntu 18.04 i get following Error:

Traceback (most recent call last):
  File "/snap/pynsource/4/pynsource-gui.py", line 1578, in <module>
    main_async()
  File "/snap/pynsource/4/pynsource-gui.py", line 1540, in main_async
    application = MainApp(0)
  File "/snap/pynsource/4/lib/python3.6/site-packages/wxasync.py", line 22, in __init__
    super(WxAsyncApp, self).__init__()
  File "/snap/pynsource/4/lib/python3.6/site-packages/wx/core.py", line 2137, in __init__
    self._BootstrapApp()
SystemError: `wxEntryStart failed, unable to initialize wxWidgets!`  (Is DISPLAY set properly?)
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by abulka** [comment]
Possibly similar to #54?

**Comment by abulka** [comment]
Are you running Ubuntu in Vmware Workstation, using Gnome running on xorg?  Because I just got this error too.

Turning off 3D acceleration in Vmware Workstation fixed it.  
Or running Gnome on Wayland (which is the default for Ubuntu 22.04).
