### ISSUE TITLE
Weird locale stuff

### ISSUE THREAD

**Issue by traverseda** [abulka/pynsource#57]
```
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)

```

After commenting that line out everything seems to work fine, although I get a popup message complaining about the en.GB locale.

**Comment by abulka** [comment]
Yikes - never seen that. Will leave this issue open just in case others encounter it.
Thanks for reporting it.

What country is your computer set to? Operating System? Keyboard?

Which line did you comment out - the actual Python 3.7 library code?

**Comment by traverseda** [comment]
Line 5 in `src/layout/coordinate_mapper.py`

As near as I can tell it's because I was having some locale issues, all my individual locale types were set but the fallback locale wasn't. I don't think that's a real problem most users are going to encounter, but adding a proper fallback to `locale.setlocale(locale.LC_ALL, "fallback_locale")` might help

**Comment by Fuzzer11** [comment]
Hi, same stuff here.

![Screenshot from 2021-02-22 10-04-48](https://user-images.githubusercontent.com/26151455/108712410-7d202400-74f5-11eb-99b1-3d099836ee82.png)

Traceback:

```
Traceback (most recent call last):
  File "pynsource-gui.py", line 369, in OnInit
    StartCoroutine(self.check_for_updates, self)
  File "/home/claus/anaconda3/lib/python3.8/site-packages/wxasync.py", line 108, in StartCoroutine
    app.StartCoroutine(coroutine, obj)
  File "/home/claus/anaconda3/lib/python3.8/site-packages/wxasync.py", line 66, in StartCoroutine
    obj.Bind(wx.EVT_WINDOW_DESTROY, lambda event: self.OnDestroy(event, obj), obj)
  File "/home/claus/anaconda3/lib/python3.8/site-packages/wx/core.py", line 1456, in _EvtHandler_Bind
    assert source is None or hasattr(source, 'GetId')
AssertionError
OnInit returned false, exiting...
```

Running over Archlinux compilation **5.10.15-arch1-1**

Python version 3.8.5
