### ISSUE TITLE
Some code imports silently fail, cause is KeyError: '_ast3.Add' 

### ISSUE THREAD

**Issue by abulka** [abulka/pynsource#59]
Some source code file imports into Pynsource silently fail, the cause is `KeyError: '_ast3.Add'` 

e.g.

```
Traceback (most recent call last):
  File "pynsource-gui.py", line 1154, in OnFileImport
    self.app.run.CmdFileImportViaDialog(mode=mode)
  File "/Users/Andy/Devel/pynsource/src/app/controller.py", line 50, in cmd_invoker_f
    self.cmd_mgr.run(cmd)
  File "/Users/Andy/Devel/pynsource/src/common/command_pattern.py", line 100, in run
    item.execute()
  File "/Users/Andy/Devel/pynsource/src/app/cmds/filemgmt.py", line 111, in execute
    super(CmdFileImportViaDialog, self).execute()
  File "/Users/Andy/Devel/pynsource/src/app/cmds/filemgmt.py", line 50, in execute
    pmodel, debuginfo = new_parser(f, options={"mode": mode})
  File "/Users/Andy/Devel/pynsource/src/parsing/api.py", line 16, in new_parser
    pmodel, debuginfo = parse(filename, log, options)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 162, in parse
    pmodel, debuginfo = _convert_ast_to_old_parser(node, filename, log, options)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 221, in _convert_ast_to_old_parser
    v.visit(node)
  File "/Users/andy/Library/Python/3.7/lib/python/site-packages/typed_ast/ast3.py", line 279, in visit
    return visitor(node)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 568, in visit_Module
    self.generic_visit(node)  # need this to keep the visiting going...
  File "/Users/andy/Library/Python/3.7/lib/python/site-packages/typed_ast/ast3.py", line 287, in generic_visit
    self.visit(item)
  File "/Users/andy/Library/Python/3.7/lib/python/site-packages/typed_ast/ast3.py", line 279, in visit
    return visitor(node)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 665, in visit_FunctionDef
    self.body(node.body)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 505, in body
    self.visit(stmt)
  File "/Users/andy/Library/Python/3.7/lib/python/site-packages/typed_ast/ast3.py", line 279, in visit
    return visitor(node)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 712, in visit_If
    self.body(node.body)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 505, in body
    self.visit(stmt)
  File "/Users/andy/Library/Python/3.7/lib/python/site-packages/typed_ast/ast3.py", line 279, in visit
    return visitor(node)
  File "/Users/Andy/Devel/pynsource/src/parsing/core_parser_ast.py", line 596, in visit_AugAssign
    self.write(" " + BINOP_SYMBOLS[as_str(type(node.op))].replace("<", "&lt;") + "= ")
KeyError: '_ast3.Add'
```

Affects version 1.74.
Am looking into this.

**Comment by abulka** [comment]
False alarm, only affected my development environment where I had typed_ast 1.4.0 installed instead of the required typed_ast==1.1.1

**Comment by brauliobarahona** [comment]
maybe I have a similar issue, I downloaded your binary for mac, the app seems to run as it can load the example diagrams, but when I try to import a python file it simply does nothing (this is my python distribution: #68) -- however, the app you distribute should have its own python and dependencies, correct?

**Comment by abulka** [comment]
Yes the Pynsource binaries come with their own inner Python and all dependencies - they won't be affected by your development environment `typed_ast` versions or anything else related to dependencies.

Please try this build of the latest master for Mac [1.76 beta 1](https://www.dropbox.com/s/2mj3zxmnq7b2zwj/pynsource-1.76beta1-macosx.zip?dl=0) which has much improved error reporting and logging. You will then be able to see what the problem is re importing your Python source code. Remember also that you won't see anything unless **classes** are detected in a Python module/file.
