### ISSUE TITLE
unclean quit with error

### ISSUE THREAD

**Issue by abulka** [abulka/pynsource#99]
Sometimes we get an error when quitting.

```
Traceback (most recent call last):
  File "pynsource-gui.py", line 1625, in <module>
  File "pynsource-gui.py", line 1593, in main_async
  File "asyncio/tasks.py", line 44, in all_tasks
RuntimeError: no running event loop
[91404] Failed to execute script pynsource-gui
Segmentation fault: 11
logout
```

Doesn't seem to affect anything, but not ideal. Investigate.

**Comment by abulka** [comment]
Possible clue - run GUI with `-Wd` to see DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10

```
/Users/andy/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/site-packages/async_lru.py:237: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  return (yield from asyncio.shield(fut, loop=_loop))
/Users/andy/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/Users/andy/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
```
